---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u6560220/public_html/ppd-laravel/
    - /bin/cp -R app DEPLOYPATH
    - /bin/cp -R bootstrap DEPLOYPATH
    - /bin/cp -R config DEPLOYPATH
    - /bin/cp -R database DEPLOYPATH
    - /bin/cp -R public DEPLOYPATH
    - /bin/cp -R resource DEPLOYPATH
    - /bin/cp -R routes DEPLOYPATH
    - /bin/cp -R storage DEPLOYPATH
    - /bin/cp -R tests DEPLOYPATH
    - /bin/cp -R .editorconfig DEPLOYPATH
    - /bin/cp -R .env.example DEPLOYPATH
    - /bin/cp -R artisan DEPLOYPATH
    - /bin/cp -R .styleci.yml DEPLOYPATH
    - /bin/cp -R composer.json DEPLOYPATH
    - /bin/cp -R package.json DEPLOYPATH
    - /bin/cp -R server.php DEPLOYPATH
    - /bin/cp -R webpack.mix.js DEPLOYPATH